### deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %{project_name}%-deployment
  namespace: smant
  labels:
    smant.app/name: %{project_name}%
spec:
  replicas: 1
  selector:
    matchLabels:
      smant.app/name: %{project_name}%
  template:
    metadata:
      namespace: smant
      labels:
        smant.app/name: %{project_name}%
    spec:
      containers:
        - name: %{project_name}%
          image: %{image_name}%
          resources:
            limits:
              memory: "1500Mi"
              cpu: "1.5"
            requests:
              cpu: "0.8"
              memory: "1000Mi"
          command: ["java","-Dloader.path=/app/lib","-jar","/app/%{project_name}%.jar"]
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
#      imagePullSecrets:
#        - name: harbor-userpass
---
### smant crm gateway service
apiVersion: v1
kind: Service
metadata:
  name: %{project_name}%
  namespace: smant
  labels:
    smant.app/name: %{project_name}%
spec:
  type: ClusterIP
  selector:
    smant.app/name: %{project_name}%
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#      nodePort: 32144
---


